source 'https://rubygems.org'

gem 'bundler', '~> 1.1'
gemspec

# gem 'xpath', :git => 'git://github.com/jnicklas/xpath.git'
gem 'tcfg', '~> 0.1'
gem 'pry'
gem 'selenium-webdriver',  '2.53.4'
gem 'xpath', '~> 2.0'

group :doc do
  gem 'redcarpet', :platforms => :mri
end
